import { DavidFumi, DrewVennemeyer, DavidRogers, ToddAHolstlaw } from 'assets';

const users = [
  {
    id: 1,
    img: ToddAHolstlaw,
    title: 'Todd A Holstlaw',
    designation: 'Founder/CEO',
    teamDesc : 'Todd Holstlaw is the Founder/CEO of Entira Capital. He has been an entrepreneur for 39 years founding several companies across multiple business sectors to include commercial real estate, development, construction, industrial painting, brokerage, property management, hospitality, investment banking and capital. In 1984, Mr. Holstlaw started his first company at 15 years old that paid for a new car and college education. He graduated with a B.S. in Economics and an MBA from Eastern Illinois University.',
    paraOne : 'In 1993, while finishing graduate school, he wrote a business plan and raised $100,000 to found Jetwash Corporation, an industrial pressure washing company that paid back his investors in 14 months. In 1994, Mr. Holstlaw started Cover-all Painting, an industrial painting company that grew to paint over 70,000,000 square feet of distribution centers.',
    paratwo : 'Equipped with enough capital, he started his first commercial real estate development company in 1995, Jetlink Development. In 2001, Mr. Holstlaw decided to vertically integrate, creating his own commercial real estatbrokerage company, PHB Realty and construction company, Bedrock Construction. In 2002 he founded his own property management company, Magellan Property Management. His network of companies was designed to control all facets of his commercial real estate portfolio.  Experiencing great success with his model, Mr. Holstlaw created three additional strategic partnerships specializing in commercial real estate development, all controlled by his vertical network of companies.',
    paraThree : 'In 2009, Mr. Holstlaw founded Hotel Restorations Ltd., a hotel renovation company designed to implement multiplication resulting in the rapid expansion in the budget hotel sector. His company successfully gained access to major hotel chains such as Extended Stay, Red Roof Inn, Motel 6 and numerous other brands. Hotel Restorations grew to renovate over 3,000 hotel rooms in 35 states. Mr. Holstlaw spent the next ten years successfully growing his companies’ annual revenues to over $50M. Mr. Holstlaw serves on several boards and has been active in non-profit organizations designed to give back to the community.',
    paraFour : 'In 2019, Mr. Holstlaw developed an innovative financing model designed to raise capital for independent colleges and universities without requiring them to use their own equity or debt by monetizing their most underutilized asset, real estate. The model combines purchase/leaseback components with annual donation factors designed to create unrestricted inexpensive capital, increasing cash flow and asset value for the institution over the lease term. In 1999, Mr. Holstlaw teamed up with Drew Vennemeyer, who has extensive knowledge in management and mathematical financing models and as a true thought partner and co-founder. He improved the model by incorporating flexibility variables giving the model the ability to customize each deal per specific institutional need. In early 2020, while refining and vetting his model, Mr. Holstlaw formed a strategic alliance with David Fumi, a bond expert with over 30 years of experience, specializing in funding over $6B in higher educational assets using Lease Revenue Bonds (LRBs). Recognizing the potential, Mr. Holstlaw incorporated Mr. Fumi’s knowledge and LRB’s into his model, creating an exceptional funding component that would produce the lowest cost of funds and flexibility of funding proceeds use. The alliance also gave the model an impressive list of former colleges and universities that successfully used LRB’s as funding vehicles and the credibility needed to overcome the difficult barriers to entry in the higher education sector.',
    paraFive : 'In 2019, Mr. Holstlaw developed an innovative financing model designed to raise capital for independent colleges and universities without requiring them to use their own equity or debt by monetizing their most underutilized asset, real estate. The model combines purchase/leaseback components with annual donation factors designed to create unrestricted inexpensive capital, increasing cash flow and asset value for the institution over the lease term. In 1999, Mr. Holstlaw teamed up with Drew Vennemeyer, who has extensive knowledge in management and mathematical financing models and as a true thought partner and co-founder. He improved the model by incorporating flexibility variables giving the model the ability to customize each deal per specific institutional need. In early 2020, while refining and vetting his model, Mr. Holstlaw formed a strategic alliance with David Fumi, a bond expert with over 30 years of experience, specializing in funding over $6B in higher educational assets using Lease Revenue Bonds (LRBs). Recognizing the potential, Mr. Holstlaw incorporated Mr. Fumi’s knowledge and LRB’s into his model, creating an exceptional funding component that would produce the lowest cost of funds and flexibility of funding proceeds use. The alliance also gave the model an impressive list of former colleges and universities that successfully used LRB’s as funding vehicles and the credibility needed to overcome the difficult barriers to entry in the higher education sector.',
    paraSix : 'CCP reverts ownership to the institution over the lease term and allows the administration to manage and use the asset without funding restrictions. The model incorporates the advantages of raising capital using LRB’s to finance through weak financials and existing debt restrictive covenants at tax-exempt bond rates. The model also has many variables that can be adjusted, making it extremely competitive with the flexibility to customize each opportunity per the individual college or university’s specific needs. Entira Capital is currently working with several independent colleges and universities located in the Midwest, East and Southern parts of America.'
  },
  {
    id: 2,
    img: DrewVennemeyer,
    title: 'Drew Vennemeyer',
    designation: 'Founder',
    teamDesc : 'Drew brings over 20 years of experience in planning, development, design, and construction. His experience includes serving as President of Quandel Construction Group in Ohio with an annual revenue volume over $100 million. Prior to that Drew was an owner of a prominent architectural design firm, DesignGroup, based in Columbus, OH.',
    paraOne : ' institutions around the country. From new construction to renovations, his project experience is wide-ranging and encompasses student housing, mixed-use facilities, classroom buildings, administration buildings, student centers, libraries, and wellness centers. Drew has orchestrated multiple public-private partnerships, including a notable development of two privatized residence halls on the campus of a public university in Northwest Ohio. He also led the planning and programming effort for one of the first Platinum LEED Certified higher education buildings in Ohio.',
    paratwo : 'Drew graduated with a Bachelor of Science in Business Administration from The Ohio State University and later earned a Masters Certificate in Facilities Management and Planning from OSU. He is a Leadership in Energy and Environmental Design (“LEED”) Accredited Professional and holds a Healthcare Construction Certification from the American Society of Healthcare Engineers.',
    paraThree : 'He was named a Central Ohio Smart 50 Award Honoree in 2018. The awards are presented to the executives leading the smartest 50 organizations in Central Ohio through innovation, impact and sustainability. Drew was recognized for excelling in Impact Areas including new building construction and expansion, talent management and development, diversification of products and services, and giving back to the community. ',
    paraFour : 'Drew was also recognized by Columbus Business First as one of its “Forty Under 40” award recipients for possessing exceptional leadership abilities, building a successful career and being active in his community. '
  },
  {
    id: 3,
    img: DavidFumi,
    title: 'David Fumi',
    designation: 'Managing Director',
    teamDesc : 'David Fumi is the Managing Director with Signet Capital, LLC and Signet Securities, LLC. Mr. Fumi’s focus at Signet is to grow its current lines of business and overall ﬁrm capabilities including public private partnerships and sale-leasebacks with colleges and universities and municipalities.  Under Mr. Fumi’s leadership, Signet Securities became a Financial Industry Regulatory Authority (FINRA) approved Municipal Financial Advisor in 2019.',
    paraOne : 'Mr. Fumi executed over $6.0 billion in ﬁnancings utilizing various capital markets structures and has structured Tax-Exempt Bonds for a large and diverse group of 501(c)(3) organizations including colleges and universities, health care facilities and manufacturing companies as well as structuring Tax Increment Financing Bonds and traditional Municipal Bond transactions.',
    paratwo : 'Prior to joining Signet, from May 2003 through May 2008, Mr. Fumi was a Managing Director with Huntington Capital Markets, the  Investment Banking Group for Huntington Bancshares. Mr. Fumi focused on the structuring of variable and ﬁxed rate Tax-Exempt and Taxable Bond transactions.',
    paraThree : 'In addition, Mr. Fumi created an approved Federal Housing Administration lender that was a wholly owned subsidiary of Huntington Bancshares and focused on multifamily and health care projects ﬁnanced through the U.S. Department of Housing and Urban Development.',
    paraFour : 'Prior to joining Huntington in 2003, Mr. Fumi was a Director with BancOne Capital Corporation and its predecessor for over 15 years and was a manager in its bond group. Mr. Fumi began his career as a member of the BancOne Capital’s Structured Finance Group as an analyst focusing on mortgage and asset securitization and on executing equity issues for Savings and Loan Associations.',
    paraFive : 'Mr. Fumi graduated from Ohio State University and holds FINRA Series 7, Series 24, Series 50, Series 53, Series 54, Series 63 and Series 79 Licenses.'
  },
  {
    id: 4,
    img: DavidRogers,
    title: 'David Rogers',
    designation: 'Bond Counsel',
    teamDesc : 'David’s practice focuses on public finance, project finance, and structured finance. His recent experience includes acting as bond counsel for state and local issuers, and representation of issuers, underwriters, placement agents, purchasers and trustees, in traditional infrastructure finance, structured finance, economic development finance, health care finance, and energy and PACE (property assessed clean energy) finance transactions; and representing issuers and bankers in transactions using securitizations and derivatives to ',
    paraOne : 'to enhance and remarket municipal bond issues. He also has experience representing both public asset owners and private lessee concessionaires in public-private partnerships. His practice concentrates in the areas of bond law, securities law, and public debt federal and state tax matters.',
    paratwo : 'He has served as bond counsel, trustees counsel, structuring counsel, underwriters counsel, developers counsel or purchasers counsel for various taxable and tax-exempt project financings, including securitizations, infrastructure, economic development and facilities finance for advanced energy, shopping centers, office buildings, stadiums, arenas and hotel facilities; as bond counsel, disclosure counsel and underwriters counsel for both tax-exempt and taxable bonds and bond programs, including energy, housing, private activity, hospital, 501(c)(3), education and traditional issues; as bond counsel for several Ohio port authorities and related taxable and tax-exempt economic development lease and bond fund programs; as bond counsel, transaction, disclosure and special tax counsel for derivative, commodities swap, interest rate swap and swaption transactions; and as bond counsel, trustees counsel, structuring counsel, disclosure counsel, underwriters counsel and special tax counsel for structured finance and corporate finance transactions, including taxable mortgage bond issues, CMBS, credit tenant leases, securitizations, P3s, secondary market transactions and governmental synthetic leases.  He acted as counsel to Queensland Investment Corporation, the lessee and concessionaire from The Ohio State University of the right to operate all parking system assets at the OSU main campus.  He also acted as placement agents counsel for multiple bond issues financing the $275 million Ernst & Young Tower Cleveland Flats project, a complex commercial real estate and public infrastructure project utilizing more than 35 funding sources.  He served as special development counsel to Cuyahoga County, Ohio, and as underwriters counsel for the bond financing of the $400 million Med Mart Convention Center Project recently completed in Cleveland. ',
    paraThree : 'He led the firms team of attorneys representing the City of Cincinnati, Ohio, negotiating and documenting its proposed public-private partnership (P3) lease of its downtown parking system to the Port of Greater Cincinnati Development Authority; which was restructured as a more traditional economic development finance transaction; and is now part of the firms team of attorneys acting as bond counsel for the City of Cincinnati. He is currently working as part of the firms team of attorneys representing the State of Ohios Department of Transportation on the $2.8 billion multi-state project to rebuild and replace the I-71/I-75 Brent Spence Bridge in Cincinnati, Ohio.',
    paraFour : 'David is also the President of our affiliate FBT Project Finance Advisors LLC, an independent municipal advisor registered with the SEC and MSRB, which consults with governmental entities and private concessionaires. The members of his FBT Project Finance Advisors team have worked to provide project finance solutions for the delivery and implementation of hundreds of infrastructure projects. They have extensive experience consulting on public and project finance projects, including design-build and DBFOM (design-build finance operate and maintain) public-private partnerships utilizing availability payments, tolls, at-risk and other innovative delivery methods. The extensive experience of the principals of FBT Project Finance Advisors is complemented by a commitment to problem-solving and finding innovative solutions, whether new solutions or ones tried before, including identification of available funding sources, analyzing SPV (special purpose vehicle) revenue finance options, P1 (traditional public finance), P2 (public-public transfers and tax-exempt finance) or P3 (public-private partnerships). It also recognizes the importance of and helps its clients with public perception, support, transparency and education.'


  },
];

export default users;
